# Generated by Django 6.0.2 on 2026-02-22 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(max_length=64)),
                ('extracted_text', models.TextField()),
                ('extracted_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenshipCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('citizenship_number', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('date_of_issue', models.CharField(max_length=64)),
                ('father_name', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizenship_cards', to=settings.AUTH_USER_MODEL)),
                ('uploaded_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizenship_card', to='document_scanner.uploadeddocument')),
            ],
        ),
    ]
