# Generated by Django 5.1.7 on 2026-02-23 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('citizenship_number', models.CharField(max_length=50, unique=True)),
                ('province', models.CharField(choices=[('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('karnali', 'Karnali'), ('koshi', 'Koshi'), ('madhesh', 'Madhesh'), ('rasuwa', 'Rasuwa')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('office', models.CharField(choices=[('kathmandu', 'Kathmandu Office'), ('pokhara', 'Pokhara Office'), ('dharan', 'Dharan Office'), ('biratnagar', 'Biratnagar Office'), ('butwal', 'Butwal Office'), ('birgunj', 'Birgunj Office')], max_length=50)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
