# Generated by Django 6.0.2 on 2026-02-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='city',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='district',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='purpose_of_visit',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.CharField(choices=[('citizenship', 'Citizenship Certificate'), ('passport_apply', 'Passport Application'), ('passport_renew', 'Passport Renewal'), ('driving_license', 'Driving License'), ('land_registration', 'Land Registration'), ('business_registration', 'Business Registration'), ('birth_certificate', 'Birth Certificate'), ('marriage_certificate', 'Marriage Certificate'), ('pan_registration', 'PAN Registration'), ('tax_consultation', 'Tax Consultation')], default='0000000000', max_length=50),
            preserve_default=False,
        ),
    ]
