# Generated by Django 6.0.2 on 2026-02-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
